# Generated by Django 5.0.1 on 2024-01-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_storedataframe_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedataframe',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
