# Generated by Django 5.0.1 on 2024-01-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_usersignupdetails_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignupdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usersignupdetails',
            name='rep_password',
        ),
    ]
